"use client";
import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
type AgentResponse={ok?:boolean;model?:string;plan?:{intent:string;scenario?:string;explanation:string};result?:{tool:string;data:unknown;authority:string};guardrails?:string[];error?:string;detail?:string};
const examples=["Verify Evelyn's valid visit evidence","Test a suspicious short visit with weak GPS","Draft a care note from recorded tasks","Find the best caregiver for Evelyn","Prepare a privacy-safe devnet proof","Summarize today's operational risk"];
export function AgentConsole(){
  const [prompt,setPrompt]=useState(examples[0]); const [response,setResponse]=useState<AgentResponse|null>(null); const [loading,setLoading]=useState(false);
  async function run(){setLoading(true);setResponse(null);try{const result=await fetch("/api/agent/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt})});setResponse(await result.json())}catch(error){setResponse({error:error instanceof Error?error.message:"Request failed"})}finally{setLoading(false)}}
  return <div className="agent-layout"><section className="panel agent-console"><div className="agent-status"><span className="live-dot"/> Groq agent online <b>Tool authority constrained</b></div><label htmlFor="agent-prompt">Ask VisitRail to inspect or prepare an operation</label><textarea id="agent-prompt" value={prompt} onChange={event=>setPrompt(event.target.value)} rows={5}/><div className="prompt-chips">{examples.map(example=><button key={example} onClick={()=>setPrompt(example)}>{example}</button>)}</div><button className="button primary wide" disabled={loading||!prompt.trim()} onClick={run}>{loading?"Routing through safe tools…":"Run live agent"}</button></section>
    <section className="panel agent-output"><div className="panel-head"><div><p className="eyebrow">Live execution trace</p><h2>Agent result</h2></div>{response?.model&&<span className="status neutral">{response.model}</span>}</div><AnimatePresence mode="wait">{!response&&!loading&&<motion.div className="empty-output" initial={{opacity:0}} animate={{opacity:1}}><span>→</span><p>Run a prompt to see the model plan, deterministic tool, authority boundary, and result.</p></motion.div>}{loading&&<motion.div className="agent-thinking" initial={{opacity:0}} animate={{opacity:1}}><i/><i/><i/><p>Model is selecting one permitted operation…</p></motion.div>}{response&&!loading&&<motion.div key={JSON.stringify(response)} className="agent-result" initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} exit={{opacity:0}}>{response.error?<div className="error-box"><strong>{response.error}</strong><p>{response.detail}</p></div>:<><div className="trace-row"><span>01 · Model plan</span><strong>{response.plan?.intent.replaceAll("_"," ")}</strong><p>{response.plan?.explanation}</p></div><div className="trace-row"><span>02 · Deterministic tool</span><strong>{response.result?.tool}</strong><small>Authority: {response.result?.authority.replaceAll("_"," ")}</small></div><pre>{JSON.stringify(response.result?.data,null,2)}</pre><div className="guardrail-list">{response.guardrails?.map(item=><p key={item}>✓ {item}</p>)}</div></>}</motion.div>}</AnimatePresence></section></div>;
}
