"use client";
import { Buffer } from "buffer";
import bs58 from "bs58";
import { motion } from "framer-motion";
import { Connection, PublicKey, Transaction, TransactionInstruction } from "@solana/web3.js";
import { useEffect, useState } from "react";
type SignedMessage=Uint8Array|{signature:Uint8Array;publicKey?:PublicKey};
type WalletProvider={isPhantom?:boolean;isSolflare?:boolean;publicKey?:PublicKey;connect:()=>Promise<{publicKey:PublicKey}>;disconnect:()=>Promise<void>;signMessage?:(message:Uint8Array,display?:string)=>Promise<SignedMessage>;signAndSendTransaction:(transaction:Transaction)=>Promise<{signature:string}>};
declare global{interface Window{solana?:WalletProvider;solflare?:WalletProvider}}
const MEMO_PROGRAM=new PublicKey("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr");
type Proof={recordHash:string;memoText:string};type Anchor={signature:string;signer:string;explorerUrl:string;cluster:string;error?:string;detail?:string};type Verification={verified:boolean;reason?:string;verifiedAt?:string;sessionToken?:string;sessionExpiresAt?:string};
export function WalletProofLab(){
  const[provider,setProvider]=useState<WalletProvider|null>(null);const[network,setNetwork]=useState<{healthy:boolean;latencyMs:number}|null>(null);const[address,setAddress]=useState("");const[verification,setVerification]=useState<Verification|null>(null);const[proof,setProof]=useState<Proof|null>(null);const[anchor,setAnchor]=useState<Anchor|null>(null);const[busy,setBusy]=useState("");
  useEffect(()=>{fetch("/api/devnet/status").then(response=>response.json()).then(setNetwork).catch(()=>setNetwork({healthy:false,latencyMs:0}))},[]);
  async function connect(){try{const wallet=window.solana??window.solflare;if(!wallet){window.open("https://phantom.app/","_blank","noopener,noreferrer");return}const result=await wallet.connect();setProvider(wallet);setAddress(result.publicKey.toBase58());setVerification(null);setAnchor(null)}catch(error){setVerification({verified:false,reason:error instanceof Error?error.message:"Wallet connection failed"})}}
  async function verifyOwnership(){if(!provider||!address)return;if(!provider.signMessage){setVerification({verified:false,reason:"This wallet does not support message signing."});return}setBusy("verify");try{const challengeResponse=await fetch("/api/wallet/challenge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({publicKey:address})});const challenge=await challengeResponse.json() as {message:string;challenge:string;error?:string};if(!challengeResponse.ok)throw new Error(challenge.error??"Challenge failed");const signed=await provider.signMessage(new TextEncoder().encode(challenge.message),"utf8");const signatureBytes=signed instanceof Uint8Array?signed:signed.signature;const verifyResponse=await fetch("/api/wallet/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({publicKey:address,message:challenge.message,challenge:challenge.challenge,signature:bs58.encode(signatureBytes)})});const result=await verifyResponse.json() as Verification;setVerification(result)}catch(error){setVerification({verified:false,reason:error instanceof Error?error.message:"Wallet verification failed"})}finally{setBusy("")}}
  async function prepare(){setBusy("prepare");const response=await fetch("/api/proofs/prepare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({visitRecordId:"visit-record-2048",finalizedAt:"2026-07-24T15:28:00Z",evidenceDigest:{status:"verified",distanceMeters:9,durationMinutes:86,noteStatus:"finalized"}})});setProof(await response.json());setAnchor(null);setBusy("")}
  async function anchorServer(){if(!proof||!verification?.verified||!verification.sessionToken)return;setBusy("server");const response=await fetch("/api/proofs/anchor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({memoText:proof.memoText,walletSession:verification.sessionToken})});setAnchor(await response.json());setBusy("")}
  async function anchorWallet(){if(!provider||!address||!proof||!verification?.verified)return;setBusy("wallet");try{const publicKey=provider.publicKey??new PublicKey(address);const connection=new Connection(process.env.NEXT_PUBLIC_SOLANA_RPC_URL??"https://api.devnet.solana.com","confirmed");const transaction=new Transaction().add(new TransactionInstruction({programId:MEMO_PROGRAM,keys:[],data:Buffer.from(proof.memoText,"utf8")}));transaction.feePayer=publicKey;const latest=await connection.getLatestBlockhash("confirmed");transaction.recentBlockhash=latest.blockhash;const{signature}=await provider.signAndSendTransaction(transaction);await connection.confirmTransaction({...latest,signature},"confirmed");setAnchor({signature,signer:publicKey.toBase58(),cluster:"devnet",explorerUrl:`https://explorer.solana.com/tx/${signature}?cluster=devnet`})}catch(error){setAnchor({signature:"",signer:address,cluster:"devnet",explorerUrl:"",error:"Wallet transaction failed",detail:error instanceof Error?error.message:"Unknown error"})}finally{setBusy("")}}
  async function disconnect(){await provider?.disconnect();setAddress("");setProvider(null);setVerification(null);setAnchor(null)}
  return <div className="proof-layout"><motion.section className="panel wallet-card" initial={false}><div className="panel-head"><div><p className="eyebrow">Browser wallet</p><h2>Connect and verify</h2></div><span className={`status ${verification?.verified?"verified":address?"review":"neutral"}`}>{verification?.verified?"Ownership verified":address?"Connected · unverified":"Not connected"}</span></div><div className="wallet-graphic"><i/><b/><span>DEVNET</span></div>{address?<><p className="wallet-address">{address}</p><button className="button primary wide" disabled={!!busy||verification?.verified} onClick={verifyOwnership}>{busy==="verify"?"Confirm in wallet…":verification?.verified?"Wallet ownership verified":"Verify wallet ownership"}</button><button className="button secondary wide wallet-disconnect" onClick={disconnect}>Disconnect wallet</button>{verification&&!verification.verified&&<p className="wallet-error">{verification.reason}</p>}</>:<button className="button dark wide" onClick={connect}>Connect Phantom / Solflare</button>}<p className="helper-copy">Connection reveals a public address. Ownership is proven separately with an expiring signed challenge; private keys never reach VisitRail.</p></motion.section>
    <motion.section className="panel proof-builder" initial={false}><div className="panel-head"><div><p className="eyebrow">Privacy-safe evidence</p><h2>Prepare and anchor proof</h2></div><span className={`status ${network?.healthy?"verified":"neutral"}`}>{network?.healthy?`Devnet live · ${network.latencyMs}ms`:"Checking devnet"}</span></div><div className="proof-steps"><div className={proof?"complete":"active"}><span>1</span><p><strong>Canonicalize record</strong><small>Only status and evidence metrics enter the digest.</small></p></div><div className={anchor?.signature?"complete":proof?"active":""}><span>2</span><p><strong>Verify signer and transact</strong><small>Browser wallets must pass ownership verification before signing.</small></p></div><div className={anchor?.signature?"complete":""}><span>3</span><p><strong>Confirm on devnet</strong><small>Verify the immutable Memo in Solana Explorer.</small></p></div></div><div className="proof-actions"><button className="button primary" onClick={prepare} disabled={!!busy}>{busy==="prepare"?"Hashing…":"Prepare SHA-256 proof"}</button><button className="button secondary" onClick={anchorWallet} disabled={!proof||!verification?.verified||!!busy}>{busy==="wallet"?"Waiting for wallet…":"Sign with verified wallet"}</button><button className="button dark" onClick={anchorServer} disabled={!proof||!verification?.verified||!!busy}>{busy==="server"?"Confirming devnet…":"Anchor with verified wallet"}</button></div>{proof&&<div className="hash-output"><span>Record hash</span><code>{proof.recordHash}</code><small>No client name, address, note text, or health detail appears on-chain.</small></div>}{anchor&&<div className={anchor.signature?"anchor-success":"error-box"}>{anchor.signature?<><span className="verified-seal">✓</span><div><strong>Confirmed on Solana devnet</strong><p>Signer {anchor.signer}</p><code>{anchor.signature}</code><a href={anchor.explorerUrl} target="_blank" rel="noreferrer">Open transaction in Explorer ↗</a></div></>:<><strong>{anchor.error}</strong><p>{anchor.detail}</p></>}</div>}</motion.section></div>
}
