"use client";
import { motion } from "framer-motion";
import { Buffer } from "buffer";
import { Connection, PublicKey, Transaction, TransactionInstruction } from "@solana/web3.js";
import { useState } from "react";
type WalletProvider={isPhantom?:boolean;isSolflare?:boolean;publicKey?:PublicKey;connect:()=>Promise<{publicKey:PublicKey}>;disconnect:()=>Promise<void>;signAndSendTransaction:(transaction:Transaction)=>Promise<{signature:string}>};
declare global { interface Window { solana?:WalletProvider; solflare?:WalletProvider } }
const MEMO_PROGRAM=new PublicKey("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr");
type Proof={recordHash:string;memoText:string}; type Anchor={signature:string;signer:string;explorerUrl:string;cluster:string;error?:string;detail?:string};
export function WalletProofLab(){
  const [provider,setProvider]=useState<WalletProvider|null>(null);const [address,setAddress]=useState("");const [proof,setProof]=useState<Proof|null>(null);const [anchor,setAnchor]=useState<Anchor|null>(null);const [busy,setBusy]=useState("");
  async function connect(){const wallet=window.solana??window.solflare;if(!wallet){window.open("https://phantom.app/","_blank","noopener,noreferrer");return}const result=await wallet.connect();setProvider(wallet);setAddress(result.publicKey.toBase58())}
  async function prepare(){setBusy("prepare");const response=await fetch("/api/proofs/prepare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({visitRecordId:"visit-record-2048",finalizedAt:"2026-07-24T15:28:00Z",evidenceDigest:{status:"verified",distanceMeters:9,durationMinutes:86,noteStatus:"finalized"}})});setProof(await response.json());setAnchor(null);setBusy("")}
  async function anchorServer(){if(!proof)return;setBusy("server");const response=await fetch("/api/proofs/anchor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({memoText:proof.memoText})});setAnchor(await response.json());setBusy("")}
  async function anchorWallet(){if(!provider?.publicKey||!proof)return;setBusy("wallet");try{const connection=new Connection(process.env.NEXT_PUBLIC_SOLANA_RPC_URL??"https://api.devnet.solana.com","confirmed");const transaction=new Transaction().add(new TransactionInstruction({programId:MEMO_PROGRAM,keys:[],data:Buffer.from(proof.memoText,"utf8")}));transaction.feePayer=provider.publicKey;const latest=await connection.getLatestBlockhash("confirmed");transaction.recentBlockhash=latest.blockhash;const {signature}=await provider.signAndSendTransaction(transaction);await connection.confirmTransaction({...latest,signature},"confirmed");setAnchor({signature,signer:provider.publicKey.toBase58(),cluster:"devnet",explorerUrl:`https://explorer.solana.com/tx/${signature}?cluster=devnet`})}catch(error){setAnchor({signature:"",signer:address,cluster:"devnet",explorerUrl:"",error:"Wallet transaction failed",detail:error instanceof Error?error.message:"Unknown error"})}finally{setBusy("")}}
  return <div className="proof-layout"><motion.section className="panel wallet-card" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}}><div className="panel-head"><div><p className="eyebrow">Browser wallet</p><h2>Connect and sign</h2></div><span className={`status ${address?"verified":"neutral"}`}>{address?"Connected":"Not connected"}</span></div><div className="wallet-graphic"><i/><b/><span>DEVNET</span></div>{address?<><p className="wallet-address">{address}</p><button className="button secondary wide" onClick={async()=>{await provider?.disconnect();setAddress("");setProvider(null)}}>Disconnect wallet</button></>:<button className="button dark wide" onClick={connect}>Connect Phantom / Solflare</button>}<p className="helper-copy">Wallet signing is explicit. VisitRail never receives the browser wallet private key.</p></motion.section>
    <motion.section className="panel proof-builder" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.08}}><div className="panel-head"><div><p className="eyebrow">Privacy-safe evidence</p><h2>Prepare and anchor proof</h2></div><span className="status neutral">Memo program</span></div><div className="proof-steps"><div className={proof?"complete":"active"}><span>1</span><p><strong>Canonicalize record</strong><small>Only status and evidence metrics enter the digest.</small></p></div><div className={anchor?.signature?"complete":proof?"active":""}><span>2</span><p><strong>Sign transaction</strong><small>Use your wallet or the funded VisitRail demo signer.</small></p></div><div className={anchor?.signature?"complete":""}><span>3</span><p><strong>Confirm on devnet</strong><small>Verify the immutable memo in Solana Explorer.</small></p></div></div><div className="proof-actions"><button className="button primary" onClick={prepare} disabled={!!busy}>{busy==="prepare"?"Hashing…":"Prepare SHA-256 proof"}</button><button className="button secondary" onClick={anchorWallet} disabled={!proof||!address||!!busy}>{busy==="wallet"?"Waiting for wallet…":"Sign with connected wallet"}</button><button className="button dark" onClick={anchorServer} disabled={!proof||!!busy}>{busy==="server"?"Confirming devnet…":"Use funded demo signer"}</button></div>{proof&&<div className="hash-output"><span>Record hash</span><code>{proof.recordHash}</code><small>No client name, address, note text, or health detail appears on-chain.</small></div>}{anchor&&<div className={anchor.signature?"anchor-success":"error-box"}>{anchor.signature?<><span className="verified-seal">✓</span><div><strong>Confirmed on Solana devnet</strong><p>Signer {anchor.signer}</p><code>{anchor.signature}</code><a href={anchor.explorerUrl} target="_blank" rel="noreferrer">Open transaction in Explorer ↗</a></div></>:<><strong>{anchor.error}</strong><p>{anchor.detail}</p></>}</div>}</motion.section></div>;
}
